import { forwardRef, useId } from 'react';
import { Search } from 'lucide-react';
import { cx } from '../utils';
import '../styles/ui.css';

function Field({ id, label, hint, error, required, loading, children, className }) { return <div className={cx('hui-field', className)} aria-busy={loading || undefined}>{label && <label htmlFor={id}>{label}{required && <span aria-hidden="true"> *</span>}</label>}{children}{error ? <span className="hui-field__error" id={`${id}-error`}>{error}</span> : hint && <span className="hui-field__hint" id={`${id}-hint`}>{hint}</span>}</div>; }
function describedBy(id, hint, error) { return error ? `${id}-error` : hint ? `${id}-hint` : undefined; }

/** @param {React.InputHTMLAttributes<HTMLInputElement> & {label?: React.ReactNode, hint?: React.ReactNode, error?: React.ReactNode}} props */
export const Input = forwardRef(function Input({ id: suppliedId, label, hint, error, className, fieldClassName, required, loading = false, unstyled = false, disabled, ...props }, ref) { const generatedId = useId(); const id = suppliedId || generatedId; const control = <input ref={ref} id={suppliedId || !unstyled ? id : undefined} required={required} disabled={disabled || loading} aria-invalid={error ? true : undefined} aria-describedby={describedBy(id, hint, error)} className={unstyled ? className : cx('hui-control', className)} {...props} />; return unstyled ? control : <Field id={id} label={label} hint={hint} error={error} required={required} loading={loading} className={fieldClassName}>{control}</Field>; });

/** @param {React.InputHTMLAttributes<HTMLInputElement> & {label?: React.ReactNode, hint?: React.ReactNode, error?: React.ReactNode}} props */
export const SearchInput = forwardRef(function SearchInput({ className, unstyled = false, loading = false, ...props }, ref) { if (unstyled) return <Input ref={ref} unstyled type={props.type || 'search'} className={className} loading={loading} {...props} />; return <div className="hui-search-input" aria-busy={loading || undefined}><Search aria-hidden="true" size={18} /><Input ref={ref} type="search" className={cx('hui-control--with-icon', className)} loading={loading} {...props} /></div>; });

/** @param {React.InputHTMLAttributes<HTMLInputElement> & {currency?: string, label?: React.ReactNode, hint?: React.ReactNode, error?: React.ReactNode}} props */
export const CurrencyInput = forwardRef(function CurrencyInput({ currency = 'EUR', className, unstyled = false, ...props }, ref) { if (unstyled) return <Input ref={ref} unstyled inputMode="decimal" className={className} {...props} />; return <div className="hui-currency-input"><Input ref={ref} inputMode="decimal" className={cx('hui-control--with-suffix', className)} {...props} /><span aria-hidden="true">{currency}</span></div>; });

/** @param {React.TextareaHTMLAttributes<HTMLTextAreaElement> & {label?: React.ReactNode, hint?: React.ReactNode, error?: React.ReactNode}} props */
export const Textarea = forwardRef(function Textarea({ id: suppliedId, label, hint, error, className, fieldClassName, required, loading = false, unstyled = false, disabled, ...props }, ref) { const generatedId = useId(); const id = suppliedId || generatedId; const control = <textarea ref={ref} id={suppliedId || !unstyled ? id : undefined} required={required} disabled={disabled || loading} aria-invalid={error ? true : undefined} aria-describedby={describedBy(id, hint, error)} className={unstyled ? className : cx('hui-control hui-textarea', className)} {...props} />; return unstyled ? control : <Field id={id} label={label} hint={hint} error={error} required={required} loading={loading} className={fieldClassName}>{control}</Field>; });

/** @param {React.InputHTMLAttributes<HTMLInputElement> & {label: React.ReactNode, description?: React.ReactNode}} props */
export const Checkbox = forwardRef(function Checkbox({ id: suppliedId, label, description, className, unstyled = false, loading = false, disabled, ...props }, ref) { const generatedId = useId(); const id = suppliedId || generatedId; if (unstyled) return <input ref={ref} id={suppliedId} type="checkbox" className={className} disabled={disabled || loading} {...props} />; return <label className={cx('hui-choice', className)} aria-busy={loading || undefined}><input ref={ref} id={id} type="checkbox" disabled={disabled || loading} {...props} /><span><strong>{label}</strong>{description && <small>{description}</small>}</span></label>; });

/** @param {React.InputHTMLAttributes<HTMLInputElement> & {label: React.ReactNode, description?: React.ReactNode}} props */
export const Switch = forwardRef(function Switch({ id: suppliedId, label, description, className, unstyled = false, loading = false, disabled, ...props }, ref) { const generatedId = useId(); const id = suppliedId || generatedId; if (unstyled) return <input ref={ref} id={suppliedId} type="checkbox" role="switch" className={className} disabled={disabled || loading} {...props} />; return <label className={cx('hui-switch', className)} aria-busy={loading || undefined}><span><strong>{label}</strong>{description && <small>{description}</small>}</span><input ref={ref} id={id} type="checkbox" role="switch" disabled={disabled || loading} {...props} /><span className="hui-switch__track" aria-hidden="true" /></label>; });

/** @param {React.SelectHTMLAttributes<HTMLSelectElement> & {label?: React.ReactNode, hint?: React.ReactNode, error?: React.ReactNode, options?: Array<{value: string|number, label: React.ReactNode, disabled?: boolean}>}} props */
export const Select = forwardRef(function Select({ id: suppliedId, label, hint, error, options = [], children, className, fieldClassName, required, loading = false, unstyled = false, disabled, ...props }, ref) { const generatedId = useId(); const id = suppliedId || generatedId; const control = <select ref={ref} id={suppliedId || !unstyled ? id : undefined} required={required} disabled={disabled || loading} aria-invalid={error ? true : undefined} aria-describedby={describedBy(id, hint, error)} className={unstyled ? className : cx('hui-control hui-select', className)} {...props}>{children || options.map(option => <option key={option.value} value={option.value} disabled={option.disabled}>{option.label}</option>)}</select>; return unstyled ? control : <Field id={id} label={label} hint={hint} error={error} required={required} loading={loading} className={fieldClassName}>{control}</Field>; });

/** @param {React.InputHTMLAttributes<HTMLInputElement> & {label?: React.ReactNode, hint?: React.ReactNode, error?: React.ReactNode}} props */
export const DatePicker = forwardRef(function DatePicker(props, ref) { return <Input ref={ref} type="date" {...props} />; });
