export const CREATE_CATEGORY_VALUE = "__CREATE_CATEGORY__";
export const CREATE_THIRD_PARTY_VALUE = "__CREATE_THIRD_PARTY__";
export const CREATE_SUBCATEGORY_VALUE = "__CREATE_SUBCATEGORY__";
export const CREATE_ACCOUNT_VALUE = "__CREATE_ACCOUNT__";
export const CREATE_ACTIVITY_VALUE = "__CREATE_ACTIVITY__";
export const CREATE_PROJECT_VALUE = "__CREATE_PROJECT__";

export const CREATE_REFERENCE_VALUES = {
  category: CREATE_CATEGORY_VALUE,
  subcategory: CREATE_SUBCATEGORY_VALUE,
  thirdParty: CREATE_THIRD_PARTY_VALUE,
  account: CREATE_ACCOUNT_VALUE,
  activity: CREATE_ACTIVITY_VALUE,
  project: CREATE_PROJECT_VALUE,
};

const CREATE_REFERENCE_VALUE_SET = new Set([
  CREATE_CATEGORY_VALUE,
  CREATE_THIRD_PARTY_VALUE,
  CREATE_SUBCATEGORY_VALUE,
  CREATE_ACCOUNT_VALUE,
  CREATE_ACTIVITY_VALUE,
  CREATE_PROJECT_VALUE,
]);

export function isCreateReferenceValue(value) {
  return CREATE_REFERENCE_VALUE_SET.has(String(value || "").trim());
}